# Generated by Django 4.0.4 on 2022-04-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=200)),
                ('ipo', models.CharField(max_length=200)),
                ('marketCapitalization', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('shareOutstanding', models.FloatField()),
                ('ticker', models.CharField(max_length=200)),
                ('weburl', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=1000)),
                ('finnhubIndustry', models.CharField(max_length=200)),
            ],
        ),
    ]
