# Generated by Django 4.0.4 on 2022-04-22 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companydailystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydailystats',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
