# Generated by Django 4.0.4 on 2022-04-26 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_companydailystats_date_companyprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydailystats',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
