# Generated by Django 4.0.4 on 2022-05-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userwatchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('openPrice', models.FloatField()),
                ('highPrice', models.FloatField()),
                ('lowPrice', models.FloatField()),
                ('closePrice', models.FloatField()),
                ('volume', models.FloatField()),
                ('percentChange', models.FloatField(blank=True, null=True)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
