# Generated by Django 4.0.4 on 2022-05-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ohlcv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDailyStats',
        ),
    ]
