# Generated by Django 4.0.4 on 2022-05-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_companydailystats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OHLCV',
        ),
    ]
