# Generated by Django 4.0.4 on 2022-05-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ohlcv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OHLCV',
            new_name='OhlcvData',
        ),
    ]
