# Generated by Django 4.0.4 on 2022-05-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_closeprice_ohlcvdata_c_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ohlcvdata',
            old_name='percentChange',
            new_name='pc',
        ),
        migrations.AlterField(
            model_name='ohlcvdata',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companyprofile'),
        ),
    ]
