# Generated by Django 4.0.4 on 2022-05-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_percentchange_ohlcvdata_pc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohlcvdata',
            name='ticker',
            field=models.CharField(max_length=200),
        ),
    ]
