# Generated by Django 4.0.4 on 2022-05-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ohlcvdata_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='defaultWatchlist',
            field=models.BooleanField(default=False),
        ),
    ]
