# Generated by Django 4.0.4 on 2022-05-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userwatchlist_isinuserwatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchlist',
            name='isInUserWatchlist',
        ),
    ]
