# Generated by Django 4.0.4 on 2022-06-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_stocksymbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockSymbol',
        ),
    ]
