# Generated by Django 4.0.4 on 2022-06-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_stocksymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('o', models.FloatField()),
                ('h', models.FloatField()),
                ('l', models.FloatField()),
                ('c', models.FloatField()),
                ('d', models.FloatField()),
                ('dp', models.FloatField()),
                ('pc', models.FloatField(blank=True, null=True)),
                ('t', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='OhlcvData',
        ),
    ]
