# Generated by Django 4.0.4 on 2022-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_dailystats_delete_ohlcvdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliableIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.BooleanField(default=False)),
            ],
        ),
    ]
