# Generated by Django 4.0.4 on 2022-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='isActive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
