# Generated by Django 4.0.4 on 2022-06-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alert_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
