# Generated by Django 4.0.4 on 2022-08-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='symbol',
            field=models.CharField(default='', max_length=200),
        ),
    ]
