# Generated by Django 4.0.4 on 2022-08-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_alert_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='symbol',
            field=models.CharField(default='', max_length=200),
        ),
    ]
