# Generated by Django 4.0.4 on 2022-08-17 07:59

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_alert_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCandles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('resolution', models.CharField(max_length=200)),
                ('fromTimestamp', models.IntegerField()),
                ('toTimestamp', models.IntegerField()),
                ('c', jsonfield.fields.JSONField()),
                ('h', jsonfield.fields.JSONField()),
                ('l', jsonfield.fields.JSONField()),
                ('o', jsonfield.fields.JSONField()),
                ('s', models.CharField(max_length=200)),
                ('t', jsonfield.fields.JSONField()),
                ('v', jsonfield.fields.JSONField()),
            ],
        ),
    ]
