# Generated by Django 4.0.4 on 2022-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_stockcandles'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcandles',
            name='localData',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
