# Generated by Django 4.0.4 on 2022-08-18 06:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_stockcandles_localdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcandles',
            name='v',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
