# Generated by Django 4.0.4 on 2022-08-18 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_stockcandles_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcandles',
            name='fetchDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
